### ISSUE TITLE
Do you have an APK available?

### ISSUE THREAD

**Issue by seflless** [rahulbobhate/Foodifai#1]
Hi,

Love the idea of this app, I'd thought to make something like this in the past. I was wondering if you had an APK I could check out. I'd love to demo this concept to someone but I'm rusty on Android development myself, I've been doing a lot of backend work for the last 2 years.

Francois

**Comment by parikshitt23** [comment]
Hi Francois,

Emailed you the apk 

Regards
Parikshit

**Comment by dondedario** [comment]
Could I also get the APK?
